# Generated by Django 3.0.5 on 2020-05-30 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('level', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='adpack-image/')),
                ('perday_revenue', models.FloatField(null=True)),
                ('expiration_day', models.IntegerField(default=60, null=True)),
                ('affiliate_earn', models.FloatField(null=True)),
                ('total_return', models.FloatField(null=True)),
                ('max_buy', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.IntegerField(blank=True, null=True)),
                ('refer_earn', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bought_adpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateField(default=datetime.datetime(2020, 5, 30, 14, 0, 41, 950318))),
                ('expiration_date', models.DateField()),
                ('total_quantity', models.IntegerField()),
                ('adpack_totalreturn', models.FloatField()),
                ('everyday_revenue', models.FloatField()),
                ('affiliate_commission', models.FloatField()),
                ('total_price', models.FloatField()),
                ('bought_adpacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0.0, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
