# Generated by Django 3.0.5 on 2020-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='current_balance',
            field=models.FloatField(default=0.0, max_length=9),
        ),
    ]
