# Generated by Django 3.0.5 on 2020-05-31 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200530_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 11, 47, 44, 459519)),
        ),
        migrations.CreateModel(
            name='adpack_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 31, 11, 47, 44, 460902))),
                ('today_revenue', models.FloatField()),
                ('bought_adpack_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bought_adpack')),
            ],
        ),
    ]
