# Generated by Django 3.0.5 on 2020-06-08 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200608_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpack_update',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 9, 34, 14, 669134)),
        ),
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 9, 34, 14, 667627)),
        ),
        migrations.AlterField(
            model_name='pm_accounts',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
