# Generated by Django 3.0.5 on 2020-06-08 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200608_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pm_accounts',
            old_name='email',
            new_name='pm_account',
        ),
        migrations.AlterField(
            model_name='adpack_update',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 9, 45, 3, 265756)),
        ),
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 9, 45, 3, 264306)),
        ),
    ]
