# Generated by Django 3.0.5 on 2020-06-08 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200608_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_accounts',
            name='account_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='adpack_update',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 11, 4, 36, 323406)),
        ),
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 11, 4, 36, 321954)),
        ),
    ]
