# Generated by Django 3.0.5 on 2020-06-09 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_auto_20200608_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpack_update',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 3, 35, 34, 340035)),
        ),
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 3, 35, 34, 338466)),
        ),
        migrations.CreateModel(
            name='withdraw_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('payment_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
