# Generated by Django 3.0.5 on 2020-06-26 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200609_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent_accounts',
            options={'verbose_name': 'user agent accounts', 'verbose_name_plural': 'user agent accounts'},
        ),
        migrations.AlterModelOptions(
            name='bank_accounts',
            options={'verbose_name': 'user bank accounts', 'verbose_name_plural': 'user bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='pm_accounts',
            options={'verbose_name': 'user perfectMoney accounts', 'verbose_name_plural': 'user perfectMoney accounts'},
        ),
        migrations.AlterModelOptions(
            name='withdraw_requests',
            options={'verbose_name': 'user withdraw requests', 'verbose_name_plural': 'user withdraw requests'},
        ),
        migrations.AlterField(
            model_name='adpack_update',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bought_adpack',
            name='buying_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdraw_requests',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
