# Generated by Django 3.0.5 on 2020-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200626_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_requests',
            name='payment_error',
            field=models.BooleanField(default=False),
        ),
    ]
