# Generated by Django 3.0.5 on 2020-06-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_withdraw_requests_payment_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='parfectmoney', max_length=40)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user deposit history',
                'verbose_name_plural': 'user deposit history',
            },
        ),
    ]
