# Generated by Django 3.0.5 on 2020-05-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200427_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
